### ISSUE TITLE
po2json dependency ist out of date

### ISSUE THREAD

**Issue by Thorbenl** [perchlabs/po-loader#12]
Hey :) Latest LTS for node is `16+` and we are depending on your loader in our config.

Would it be possible to either move the po loader to this package and maintain it, or can you somehow get in contact with the maintainer?
```
[build:embeddable-client-prod] (node:57182) [DEP0128] DeprecationWarning: Invalid 'main' field in '/worki/frontend/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author
```

this will stop working for latest lts. :/ 

Any ideas? Security audit reuqires us to run latest lts, so we cant really stay on 14

**Comment by dschissler** [comment]
@Thorbenl Try the new package `0.7.0`.  I'm not current running po2json in my projects and so I can't test it for you.
